# Generated by Django 5.1.1 on 2025-03-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=16)),
                ('adresse', models.TextField()),
                ('description', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
