# Generated by Django 5.1.1 on 2025-04-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etablissement',
        ),
    ]
