# Generated by Django 5.1.1 on 2025-04-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applis', '0002_delete_etablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=16)),
                ('adresse', models.TextField()),
                ('description', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=16)),
                ('Email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
